general {
    # Optn=command,action (Prevents launching multiple lock screens)
    # lock_cmd = pidof hyprlock || hyprlock

    # Optn=command,action (Locks screen before system goes to sleep)
    # before_sleep_cmd = loginctl lock-session

    # Optn=command,action (Wakes screen up after resuming from sleep)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Optn=timeout_seconds,action (Lock screen after 5m)
# listener {
#     timeout = 180
#     on-timeout = loginctl lock-session
# }

# Optn=timeout_seconds,action (Screen off after 10m)
listener {
    timeout = 119
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Optn=timeout_seconds,action (Suspend PC after 30m)
listener {
    timeout = 360
    on-timeout = systemctl suspend
}
